export const celebratoryChirps = [
  "Chirp heard! 📢",
  "Emoji message flyin'! 🚀",
  "Chirp vibes activated! 😎",
  "Chirp game strong! 💪",
  "Share the chirp joy! 💗",
  "You chirped it! 😉",
  "Chirp mission complete! ✅",
  "Chirp on fleek! 🔥",
  "Chirp it loud, chirp it proud! 🗣️",
  "That chirp tho! 👌",
  "Chirp like a champ! 🏆",
  "Chirp like no one's watching! 💃",
  "Emoji power unleashed! ⚡️",
  "Chirp vibes contagious! 😁",
  "Chirp it real good! 👍",
  "Chirp yeah! 🙌",
  "Chirp, chirp, hooray! 🎉",
  "Your chirp is trending! 🔥",
  "Chirp like a pro! 😎",
  "Chirp of the day! 🌟",
  "Emoji message rockin'!🤘",
  "Your chirp = pure awesomeness! 🤩",
  "Chirp like a legend! 👑",
  "Chirp game unstoppable! 💪",
  "That chirp is 🔥🔥🔥",
  "Chirp vibes poppin'! 💥",
  "Get your chirp on! 🥳",
  "Chirp it up! ⬆️",
  "Emoji expression on point! 👌",
  "Chirp heard worldwide! 🌎",
  "Chirp mic drop! 🎤💥",
  "You're a chirpin' superstar! 🌟",
  "Chirp well chirped! 👏",
  "Spread those chirp wings! 🐦",
  "Chirp, chirp, celebrate! 🎉",
  "Chirp game elevated! 🚀",
  "That chirp is a vibe! 😎",
  "Chirp louder! 📣",
  "Unleash the emoji power! ⚡️",
  "Chirp energy overload! 💥",
  "Chirpin' with style! ✨",
  "Chirp like a boss! 😎",
  "Those emoji skills! 🔥",
  "Chirp game undefeated! 🏆",
  "Emoji message on fire! 🔥",
  "Chirp vibes unstoppable! ✨",
  "Chirp louder for the people in the back! 😉",
  "Make some chirp noise! 📢",
  "The world awaits your next chirp! 🌎",
  "Chirp creativity unleashed! 🎨",
];

export const errorChirps = [
  "Where's the emoji? 😉",
  "Emojis make chirps fly! 🚀",
  "This chirp needs a splash of emoji ✨",
  "Emojis are the way to chirp! 👍",
  "Chirp it with emojis! 🎉",
  "Empty chirp? No way! 😉",
  "Let those emojis loose! 😜",
  "We ❤️ emojis here!",
  "Show us your emoji skills! 😎",
  "Emojis = Chirp magic ✨",
  "Express yourself...in emoji! 😄",
  "Chirp without emojis? 🤔",
  "More emojis, please! 😄",
  "Your emojis are waiting! 🌟",
  "Say it with an emoji!💥",
  "Emoji-less chirps are sad chirps 🥺",
  "Make your chirp pop with emojis! 💥",
  "Emojis are the life of the party 🎉",
  "Chirp louder with emojis! 💪",
  "We're all about those emoji vibes 😎",
];

export const placeholders = [
  "🤔 Feeling chatty? Spill the tea!",
  "🤯 Mind blown? Let your thoughts fly!",
  "📢 Got something to say? Shout it out!",
  "🤫 Secrets to share? Whisper them here...",
  "💭 Idea explosion? Let your creativity loose!",
  "💬 Let's get the conversation started!",
  "✨ Feeling inspired? Share the spark!",
  "Share your thoughts 🤯...",
  "🎉 Feeling festive? Spread the good vibes!",
  "💡 Lightbulb moment? Brighten our day!",
  "❓ Questions swirling? Let's find answers!",
  "📚 Story to tell? We're all ears!",
  "🌈 Imagination running wild? Paint us a picture!",
  "🌟 Time to shine? Show us what you've got!",
  "🎈 Feeling lighthearted? Share the giggles!",
  "💭 Think out loud...",
  "🧠 Brain buzzing? Let's brainstorm!",
  "🕵️‍♀️  Something on your mind? Unravel the mystery!",
  "😕 Feeling puzzled? Let's solve it together!",
  "👀  Something caught your eye? Show and tell!",
  "🌎  Global perspective? Widen our world!",
  "🚀  Ready for takeoff? Blast off with your ideas!",
  "🎤  Got the mic? Take the stage!",
  "🥁  Feeling the beat? Share your rhythm!",
  "🎨  Artistic streak? Let's see your masterpiece!",
  "🎬 Lights, camera, action! What's your story?",
  "📚 Bookworm alert? Share your latest read!",
  "🍿 Movie buff? Spill your recommendations!",
  "🎵  Music lover? Share your favorite tunes!",
  "🎮  Game on! What are you playing?",
  "💪  Feeling motivated? Inspire us all!",
  "🧘‍♀️  Zen vibes? Find your inner peace!",
  "🤣  Something funny? Crack us up!",
  "🍽️  Foodie alert? Share your favorite recipe!",
  "🗺️  Wanderlust dreams? Tell us your travel wish list!",
  "🌧️ Feeling cozy? Embrace the snuggles!",
  "☀️  Soaking up the sunshine? Spread the warmth!",
  "🌊  Beach vibes? Take us to the shore!",
  "⛰️  Mountain lover?  Show us the views!",
  "❄️  Winter wonderland? Share the magic!",
  "🌸  Spring blooms? Capture the beauty!",
  "🍂  Autumn colors? Show us the cozy vibes!",
  "🌟 Gazing at the stars? Make a wish!",
  "🌙  Night owl? Embrace the quiet!",
  "☕  Coffee break? Let's catch up!",
  "🍵  Tea time? Time to relax!",
  "🐕  Dog lover? Show us your furry friends!",
  "🐈  Cat person? Time for adorable overload!",
  "🐦 Nature enthusiast? Share your sightings!",
  "🌱 Green thumb? Show off your garden!",
  "♻️  Eco-conscious? Share your green tips!",
  "🛠️  DIY expert? Teach us your tricks!",
  "📚 Avid reader? What's on your bookshelf?",
  "✍️ Wordsmith? Share your writing!",
  "📷 Shutterbug?  Show us your best shot!",
  "🚲 Adventurer at heart? Tell us about your explorations!",
];
