name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DATABASE_URL: "https://fake-database.com"
  UPSTASH_REDIS_REST_URL: "https://fake-redis.com"
  UPSTASH_REDIS_REST_TOKEN: "fake-token"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Run types check
        run: npm run typecheck

      - name: Run lint
        run: npm run lint
